write_step – x3d2
write_step Subroutine
26 statements
Source File
public subroutine write_step(self, solver, t, u, v, w)
Computes and reports monitoring quantities, writing to both stdout and the monitoring file. Divergence: max and mean (should be ~0)
Type Bound
monitoring_t
Arguments
Type Intent Optional Attributes Name
class(monitoring_t), intent(inout) :: self
class(solver_t), intent(inout) :: solver
real(kind=dp), intent(in) :: t
class(field_t), intent(in) :: u
class(field_t), intent(in) :: v
class(field_t), intent(in) :: w
Calls
Called by
Call graph
write_step calls field_max_mean, curl, divergence_v2p, get_block, release_block, scalar_product
curl calls curl, get_block, release_block, reorder, tds_solve, vecadd
divergence_v2p calls divergence_v2c
get_block calls create_block, set_shape
divergence_v2c calls get_block, release_block, reorder, tds_solve, vecadd
postprocess_channel calls write_step
postprocess_cylinder calls write_step
postprocess_generic calls write_step
postprocess_tgv calls write_step